{
 "title": "HPE OneView using InfluxDB/Telegraf and Exec",
 "description": "POSH scripts running in VM-W2022",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "VC Frame3-Interconnect3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "alias": "Q1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Frame3-Interconnect3-Q1",
     "select": [
      [
       { "params": [ "receiveKilobitsPerSec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Q2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Frame3-Interconnect3-Q2",
     "select": [
      [
       { "params": [ "receiveKilobitsPerSec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Q5:1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Frame3-Interconnect3-Q5-1",
     "select": [
      [
       { "params": [ "receiveKilobitsPerSec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Q5:2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Frame3-Interconnect3-Q5-2",
     "select": [
      [
       { "params": [ "receiveKilobitsPerSec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Q5:3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Frame3-Interconnect3-Q5-3",
     "select": [
      [
       { "params": [ "receiveKilobitsPerSec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VC Frame3-Interconnect6",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "alias": "Q1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Frame3-Interconnect6-Q1",
     "select": [
      [
       { "params": [ "receiveKilobitsPerSec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Q2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Frame3-Interconnect6-Q2",
     "select": [
      [
       { "params": [ "receiveKilobitsPerSec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Q5:1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Frame3-Interconnect6-Q5-1",
     "select": [
      [
       { "params": [ "receiveKilobitsPerSec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Q5:2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Frame3-Interconnect6-Q5-2",
     "select": [
      [
       { "params": [ "receiveKilobitsPerSec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Q5:3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Frame3-Interconnect6-Q5-3",
     "select": [
      [
       { "params": [ "receiveKilobitsPerSec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Q5:4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Frame3-Interconnect6-Q5-4",
     "select": [
      [
       { "params": [ "receiveKilobitsPerSec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Carbon footprint Report - Oneview appliances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Frame1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "composer.lj.lab_Carbon_Report",
     "select": [
      [
       { "params": [ "Frame1_TotalEmissionsPerDay" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Frame2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "composer.lj.lab_Carbon_Report",
     "select": [
      [
       { "params": [ "Frame2_TotalEmissionsPerDay" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Frame3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "composer.lj.lab_Carbon_Report",
     "select": [
      [
       { "params": [ "Frame3_TotalEmissionsPerDay" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Frame4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "composer.lj.lab_Carbon_Report",
     "select": [
      [
       { "params": [ "Frame4_TotalEmissionsPerDay" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ESX5-2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oneview.lj.lab_Carbon_Report",
     "select": [
      [
       {
        "params": [
         "esx5-2-ilo.lj.lab_TotalEmissionsPerDay"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ESX5-3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oneview.lj.lab_Carbon_Report",
     "select": [
      [
       {
        "params": [
         "esx5-3-ilo.lj.lab_TotalEmissionsPerDay"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "LIOGW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oneview.lj.lab_Carbon_Report",
     "select": [
      [
       {
        "params": [
         "ilo-LIOGW.lj.lab_TotalEmissionsPerDay"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "RDS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oneview.lj.lab_Carbon_Report",
     "select": [
      [
       {
        "params": [
         "ilo-RDS.lj.lab_TotalEmissionsPerDay"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FDZ360G10-2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oneview.lj.lab_Carbon_Report",
     "select": [
      [
       {
        "params": [
         "ilo-fdz360g10-2.lj.lab_TotalEmissionsPerDay"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Carbon footprint Report - Oneview appliances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "TOTAL Carbon emissions",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "OneView_Carbon_Report",
     "select": [
      [
       { "params": [ "TotalEmissionsPerDay" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Frames - Ambiant temperature",
   "type": "timeseries",
   "description": "Ambiant temperature",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "Frame1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Frame1",
     "select": [
      [
       { "params": [ "AmbientTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Frame2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Frame2",
     "select": [
      [
       { "params": [ "AmbientTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Frame3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Frame3",
     "select": [
      [
       { "params": [ "AmbientTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Frame4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Frame4",
     "select": [
      [
       { "params": [ "AmbientTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Frames - Power consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 16 },
   "targets": [
    {
     "alias": "Frame1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Frame1",
     "select": [
      [
       { "params": [ "AveragePower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Frame2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Frame2",
     "select": [
      [
       { "params": [ "AveragePower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Frame3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Frame3",
     "select": [
      [
       { "params": [ "AveragePower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Frame4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Frame4",
     "select": [
      [
       { "params": [ "AveragePower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Computes - Ambiant Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "ESX-1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Esx-1",
     "select": [
      [
       { "params": [ "AmbientTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Frame3-Bay12",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Frame3-bay12",
     "select": [
      [
       { "params": [ "AmbientTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Frame3-Bay7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Frame3-bay7",
     "select": [
      [
       { "params": [ "AmbientTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Computes - CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "ESX-1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Esx-1",
     "select": [
      [
       { "params": [ "CpuUtilization" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Frame3-Bay12",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Frame3-bay12",
     "select": [
      [
       { "params": [ "CpuUtilization" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Frame3-Bay7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Frame3-bay7",
     "select": [
      [
       { "params": [ "CpuUtilization" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Computes - Average Power consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "ESX-1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Esx-1",
     "select": [
      [
       { "params": [ "AveragePower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Frame3, bay 7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Frame3-bay12",
     "select": [
      [
       { "params": [ "AveragePower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Frame3, bay 12",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Frame3-bay7",
     "select": [
      [
       { "params": [ "AveragePower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}