---
# Information required for Ansible to manage the Windows hosts
ansible_user: administrator
ansible_password: "{{ administrator_password }}"

ansible_connection: winrm
ansible_winrm_transport: ntlm
ansible_port: 5985

# The following is necessary for Python 2.7.9+ when using default WinRM self-signed certificates:
ansible_winrm_server_cert_validation: ignore

