---
- name: Gather information from enclosures/frames managed by HPE OneView
  hosts: localhost
  collections:
    - hpe.oneview
  gather_facts: no

  vars:
    config: "{{ playbook_dir }}/oneview_config.json"


  tasks:
  - name: Gather facts about all Enclosures
    oneview_enclosure_facts:
      config: "{{ config }}"
    #delegate_to: localhost

  # - debug: var=enclosures
  - debug: msg="Enclosure names {{enclosures | map(attribute='name') | list }}"


  - name: Gathering facts about all Logical Enclosures
    oneview_logical_enclosure_facts:
      config: "{{ config }}"
    #delegate_to: localhost

  - debug: msg="Logical Enclosure names {{logical_enclosures | map(attribute='name') | list }}"

  - name: Gathering facts about all Server Hardware Serial numbers
    oneview_server_hardware_facts:
      config: "{{ config }}"
    #delegate_to: localhost
    
    #- debug: msg={{server_hardwares}}
  - debug: msg="Server Serial Numbers {{server_hardwares | map(attribute='serialNumber') | list }}"

  # - debug:
  #     var: hostvars[inventory_hostname]
  #     verbosity: 1