---
- hosts: localhost
  vars:
    - config: "{{ playbook_dir }}/oneview_config.json"
  tasks:
    - name: Create OneView backup
      script: create_backup.sh
      delegate_to: localhost
      register: backup
    
    - debug: var=backup.stdout



    