---
# This playbook can be used to perform an automated installation/upgrade of HPE firmware and drivers on VMware ESXi
#
# Supported with Synergy Gen10/Gen10+ servers
#
# Requirement: 
# - Synergy Service Package must be present in the HPE Oneview repository
# - AMS and iSUT VIBs must be present in the files/<esxi_build> folder of the Ansible project
# - Server(s) must be under the control of a HPE OneView Server Profile
# - The SSH public key of the Ansible control node must be present in .ssh/authorized_keys on host(s) you wish to upgrade

# This playbook performs the following steps on each inventory host:
# - places ESXi host into maintenance mode with VSAN ensureObjectAccessibility compliant mode 
# - installs AMS/iSUT if they are not already installed
# - configures iSUT mode to allow OS driver updates via HPE OneView Server Profile
# - updates the OneView Server Profile to enable Firmware and OS Drivers upgrades using iSUT 
# - updates the OneView Server Profile to use the defined baseline
# - monitors the status of the upgrade process 
# - if required, reboots the ESXi host once or more times for HPE drivers/firmware activation 
# - exits ESXi host from maintenance mode 
# - displays an installation complete message once the server is back online

- name: Perform an automated installation/upgrade of HPE firmware and drivers on VMware ESXi
  hosts: ESX
  collections:
    - hpe.oneview
  gather_facts: no
  vars_files:
    - vars/vcentervars.yml
    #- vars/encrypted_credentials.yml
  vars:
    # HPE Synergy Composer configuration
    - config: "{{ playbook_dir }}/oneview_config.json"

    # Folder located in <Ansible_project_dir>/files to store the VIB files
    # You can use the template name: ESXi_<build>. <build> is found in boot.cfg in the root of ESXi ISO
    - esxi_build: "ESXi_17630552"
    # Minimum Packages required for automated drivers and Firmware installation
    - AMS_package: "HPE_bootbank_amsd_701.11.8.0.15-1OEM.701.0.0.16850804.vib"
    - iSUT_package: "HPE_bootbank_sut_701.2.9.0.44-1OEM.701.0.0.16850804.vib"

    # Synergy Service Pack must be present in Oneview repository
    # - synergy_service_pack_version: "SY-2021.05.03"
    - synergy_service_pack_version: "SY-2021.11.01"
    
    - domain: "lj.lab"
    - inventory_fqdn: "{{ inventory_hostname | lower }}.{{ domain }}"

  tasks:

# Collecting facts on firmware baseline 
    - name: Gathering facts about Firmware bundles
      oneview_firmware_driver_facts:
        config: "{{ config }}"
      delegate_to: localhost

    # - debug: var=firmware_drivers

    - name: Capturing firmware bundle "{{ synergy_service_pack_version }}" uri
      set_fact:
        firmware_Baseline_Uri: "{{ (firmware_drivers | selectattr('version', 'equalto', synergy_service_pack_version) |  map(attribute='uri') | list)[0] }}"

    # - debug: var=firmware_Baseline_Uri

# Placing ESXi host into maintenance mode with VSAN ensureObjectAccessibility compliant mode 

    - name: Entering VSAN-Compliant Maintenance Mode
      community.vmware.vmware_maintenancemode:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        esxi_hostname: '{{ inventory_fqdn }}'
        vsan: ensureObjectAccessibility
        evacuate: true
        timeout: 3600
        state: present
        validate_certs: false
      register: status
      delegate_to: localhost

    - debug: var=status.msg

# Installing iSUT and AMS on the server for online installation of HPE drivers for ESXi

    - name: Copying HPE iSUT VIB file to {{ inventory_hostname }} if not present
      copy:
        src: files/{{ esxi_build }}/{{ iSUT_package }}
        dest: /tmp/sut.vib
        mode: 0755
 
    - name: Copying HPE AMS VIB file to {{ inventory_hostname }} if not present
      copy:
        src: files/{{ esxi_build }}/{{ AMS_package }}
        dest: /tmp/amsd.vib
        mode: 0755

# AMS      
    - name: Searching for existing VIB AMS installation
      shell: esxcli software vib list | grep -w amsd
      register: vibs
      changed_when: false
      ignore_errors: yes

    - debug: var=vibs.stdout

    - name: Installing AMS (if not installed)
      shell: esxcli software vib install -v /tmp/amsd.vib
      when: "'amsd' not in vibs.stdout"
      register: vibs

    - debug: var=vibs.stdout  
      when: vibs.stdout is defined

# SUT
    - name: Searching for existing VIB SUT installation
      shell: esxcli software vib list | grep -w sut
      register: vibs
      changed_when: false
      ignore_errors: yes

    - debug: var=vibs.stdout

    - name: Installing SUT (if not installed)
      shell: esxcli software vib install -v /tmp/sut.vib
      when: "'sut' not in vibs.stdout"
      register: vibs

    - debug: var=vibs.stdout  
      when: vibs.stdout is defined

    - name: Configuring iSUT mode to allow OS driver updates via HPE OneView Server Profile
      command: 
        sut -set mode=autodeploy 
        #sut -set mode=AutoDeployReboot
        #sut -set mode=AutoStage
        #sut -set mode=OnDemand
      register: sut_status

    - debug: msg="{{ sut_status.stdout }}"

# Changing the OneView Server Profile to enable OS drivers installation using the defined SSP/SPP.    

    - name: Updating Server Profile to enable Firmware and OS Drivers upgrade using SUT and {{ synergy_service_pack_version }} firmware baseline
      oneview_server_profile:
        config: "{{ config }}"
        state: "present"
        data:
          name: "{{ inventory_hostname }}"
          firmware:
            firmwareInstallType: "FirmwareAndOSDrivers" 
            # firmwareInstallType: "FirmwareOnlyOfflineMode"
            firmwareBaselineUri: "{{ firmware_Baseline_Uri }}"
      delegate_to: localhost
      register: result

    - debug: msg="{{ result.msg }}"

# Waiting for HPE components to be installed (if any)

    - name: Waiting for HPE components to be staged and installed... (if any)
      oneview_server_hardware_facts:
        config: "{{ config }}"
        name: "{{ server_hardware.name }}"
      retries: 100
      delay: 30 
      until: >
        (server_hardwares.serverSettings.firmwareAndDriversInstallState.installState == "Activated") 
        or 
        (server_hardwares.serverSettings.firmwareAndDriversInstallState.installState == "InstalledPendingReboot")
        or 
        (server_hardwares.serverSettings.firmwareAndDriversInstallState.installState == "ActivateFailed")
        or 
        (server_hardwares.serverSettings.firmwareAndDriversInstallState.installState == "InstallFailed")
        or 
        (server_hardwares.serverSettings.firmwareAndDriversInstallState.installState == "StageFailed")
      delegate_to: localhost

    - set_fact:
        server_up_to_date: true
      when: server_hardwares.serverSettings.firmwareAndDriversInstallState.installState == "Activated"
      
# If required, rebooting host for the HPE drivers/firmware activation

    - name: Rebooting host (if required) for the HPE firmware and/or OS drivers activation and waiting for it to restart 
      reboot:
        msg: "Reboot initiated by Ansible"
        reboot_timeout: 2700 # 45mn
        pre_reboot_delay: 10
        post_reboot_delay: 30
      when: server_hardwares.serverSettings.firmwareAndDriversInstallState.installState == "InstalledPendingReboot"

# Waiting for HPE components to be installed (if any) after the first reboot 

    - name: Waiting for more HPE components to be installed... (if any)
      oneview_server_hardware_facts:
        config: "{{ config }}"
        name: "{{ server_hardware.name }}"
      retries: 50
      delay: 10 
      until: >
        (server_hardwares.serverSettings.firmwareAndDriversInstallState.installState == "Activated") 
        or 
        (server_hardwares.serverSettings.firmwareAndDriversInstallState.installState == "InstalledPendingReboot")
        or 
        (server_hardwares.serverSettings.firmwareAndDriversInstallState.installState == "ActivateFailed")
        or 
        (server_hardwares.serverSettings.firmwareAndDriversInstallState.installState == "InstallFailed")
        or 
        (server_hardwares.serverSettings.firmwareAndDriversInstallState.installState == "StageFailed")
      delegate_to: localhost
      when:  server_hardwares.serverSettings.firmwareAndDriversInstallState.installState == "InstalledPendingReboot"
    
# If required, rebooting host a second time for the additional HPE drivers/firmware activations

    - name: Rebooting host again (if required) for the other HPE firmware and/or OS drivers activation and waiting for it to restart 
      reboot:
        msg: "Reboot initiated by Ansible"
        reboot_timeout: 1200 # 20mn
        pre_reboot_delay: 10
        post_reboot_delay: 30
      when: server_hardwares.serverSettings.firmwareAndDriversInstallState.installState == "InstalledPendingReboot"

# Waiting for HPE components to be installed (if any) after the second reboot (if any)

    - name: Waiting for SUT status after the second reboot (if any)
      oneview_server_hardware_facts:
        config: "{{ config }}"
        name: "{{ server_hardware.name }}"
      retries: 50
      delay: 10 
      until: >
        (server_hardwares.serverSettings.firmwareAndDriversInstallState.installState == "Activated") 
        or 
        (server_hardwares.serverSettings.firmwareAndDriversInstallState.installState == "InstalledPendingReboot")
        or 
        (server_hardwares.serverSettings.firmwareAndDriversInstallState.installState == "ActivateFailed")
        or 
        (server_hardwares.serverSettings.firmwareAndDriversInstallState.installState == "InstallFailed")
        or 
        (server_hardwares.serverSettings.firmwareAndDriversInstallState.installState == "StageFailed")
      delegate_to: localhost
      when:  server_hardwares.serverSettings.firmwareAndDriversInstallState.installState == "InstalledPendingReboot"       

# Exiting ESXi host from maintenance mode 

    - name: Exiting Maintenance Mode
      community.vmware.vmware_maintenancemode:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        esxi_hostname: '{{ inventory_fqdn }}'
        vsan: ensureObjectAccessibility
        evacuate: true
        timeout: 3600
        state: absent
        validate_certs: false
      register: status
      delegate_to: localhost
      when:  server_hardwares.serverSettings.firmwareAndDriversInstallState.installState == "Activated" 

    - debug: var=status.msg
      when:  server_hardwares.serverSettings.firmwareAndDriversInstallState.installState == "Activated" 

# Displaying the upgrade completion message 

    - name: Displaying message when components are already up-to-date
      debug: 
        msg: 
         - '{{ inventory_hostname }} upgrade not required !'
         - 'HPE firmware and/or OS drivers from {{ synergy_service_pack_version }} are already installed and activated on the server'
         - 'The server has been placed out of maintenance'
      when: server_up_to_date is defined
              
    - name: Displaying upgrade completed successfully message
      debug: 
        msg: 
         - '{{ inventory_hostname }} upgrade completed successfuly !'
         - 'HPE firmware and/or OS drivers from {{ synergy_service_pack_version }} are installed and activated on the server'
         - 'The server has been placed out of maintenance'
      when: 
        - server_hardwares.serverSettings.firmwareAndDriversInstallState.installState == "Activated"
        - server_up_to_date is not defined

    - name: Displaying upgrade error message
      debug: 
        msg: 
         - '{{ inventory_hostname }} upgrade failure !'
         - "The installation state information of the firmware and/or OS drivers on the server is '{{ server_hardwares.serverSettings.firmwareAndDriversInstallState.installState }}'"
         - 'Check the OneView console for more information - The server has been kept in maintenance mode'
      when: >
        (server_hardwares.serverSettings.firmwareAndDriversInstallState.installState == "ActivateFailed") 
        or 
        (server_hardwares.serverSettings.firmwareAndDriversInstallState.installState == "InstallFailed") 
        or 
        (server_hardwares.serverSettings.firmwareAndDriversInstallState.installState == "StageFailed")