---
- name: Ansible OneView Synergy playbook to remove deployed servers 
  hosts: localhost
  collections:
    - hpe.oneview
  gather_facts: no
  vars:
    - config: "{{ playbook_dir }}/composer1_config.json"

  tasks:
    - set_fact: 
        hostname="RHEL-1_Ansible_deployment"

    - name : Getting server profile(s) information
      oneview_server_profile:
         config: "{{ config }}"
         state: "present"
         data:
            name: "{{ hostname }}"
      delegate_to: localhost

    #- debug: var=server_hardware

    - name: Powering off the server hardware [{{ server_hardware.name }}]
      oneview_server_hardware:
        config: "{{ config }}"
        state: power_state_set
        data:
            name : "{{ server_hardware.name }}"
            powerStateData:
                powerState: "Off"
                powerControl: "PressAndHold"
      delegate_to: localhost

    - name: Deleting Server Profile [{{ hostname }}]
      oneview_server_profile:
        config: "{{ config }}"
        state: "absent"
        data:
          name: "{{ hostname }}"
      delegate_to: localhost