---
- name: Ansible OneView Synergy playbook to deploy Compute Module(s) using a Server Profile Template
  hosts: RHEL
  gather_facts: no
  vars:
    - config: "{{ playbook_dir }}/oneview_config.json"
    - server_template: "HPE Synergy 480 Gen9 with Local Boot for RHEL Template"

  tasks:
    - name: Creating Server Profile [{{ inventory_hostname }}] from Server Profile Template [{{ server_template }}]
      oneview_server_profile:
        config: "{{ config }}"
        data:
          serverProfileTemplateName: "{{ server_template }}"
          name: "{{ inventory_hostname }}"
      delegate_to: localhost
      register: result

    #- debug: var=server_hardware 
    
    - name: Task result of the Server Profile(s) creation
      debug: 
        msg: "{{ result.msg }}"

    - name: Powering on the Compute Module(s) [{{ server_hardware.name }}]
      oneview_server_hardware:
        config: "{{ config }}"
        state: power_state_set
        data:
            name : "{{ server_hardware.name }}"
            powerStateData:
                powerState: "On"
                powerControl: "MomentaryPress"
      delegate_to: localhost

    - debug: 
        msg: "The server is located in {{ server_hardware.name }}"


    # - name: Collecting Compute Module(s) information
    #   oneview_server_profile_facts:
    #     config: "{{ config }}"
    #     name: "{{ inventory_hostname }}"
    #   delegate_to: localhost

    # - name: set variable for the enclosure uri  
    #   set_fact:
    #     enclosureuri: "{{ server_profiles.0.enclosureUri  }}"    

    # # - debug: var=server_profiles
    # # - name: Task result of the enclosureuri
    # #   debug: 
    # #     msg: "{{ enclosureuri }}"

    # - name: Gather facts about Enclosures
    #   oneview_enclosure_facts:
    #     config: "{{ config }}"
    #   delegate_to: localhost

    # - name: Set variable for enclosure name  
    #   set_fact:
    #     enclosurename: "{{ enclosures | selectattr('uri', 'equalto', enclosureuri) | map(attribute='name') | list }}"

    # # - debug: var=enclosures
    # # - debug: msg="{{ enclosures | selectattr("uri", "equalto", enclosureuri) | map(attribute='name') | list }}"      
    # # - debug: var=enclosurename

    # - name: Displaying enclosure bay assigned to the Compute module(s)
    #   debug: 
    #    msg: "The server is located in bay {{ server_profiles | map(attribute='enclosureBay') | list }} in enclosure {{ enclosurename }}"