---
# Server Profile Template module does not allow easy modifications today as it requires, 
# especially for connections, to provide a list of all connections in order to modify a single one.
# This playbook will create a list of all required connections with the appropriate change requested on 
# one or more connections using the connection IDs and their values to be changed.

- name: Modification of the network connections of an existing Server Profile Template in HPE OneView
  hosts: localhost
  collections:
    - hpe.oneview
  vars:
    config: "{{ playbook_dir }}/oneview_config.json"

    server_profile_template_name: "RHEL_BFS"
    
    # Connection value to modify
    key: "requestedMbps"
    value: 2800
    # Connection ID to modify
    connection_ids: 
      - 1
      - 2

  tasks:
    - name: Gather facts about the Server Profile Template
      oneview_server_profile_template_facts:
        config: "{{ config }}"
        name: "{{ server_profile_template_name }}"
      delegate_to: localhost

    - set_fact:
        existing_connections: "{{ server_profile_templates[0].connectionSettings.connections }}"

    # - debug: var=existing_connections        

    - name: Collecting connections that need to be modified
      set_fact:
        connections_to_modify: "{{ connections_to_modify|default([]) + existing_connections | selectattr('id', 'equalto', item) | list }}"
      with_items: "{{ connection_ids }}"

    # - debug: var=connections_to_modify    

    - name: Settings the connections with the new value
      set_fact:
        connections_modified: "{{ connections_modified|d([]) + [item|combine({key: value |from_yaml})] }}"
      loop: "{{ connections_to_modify }}"

    # - debug: var=connections_modified

    - name: Collecting connections that do not need to be modified
      set_fact:
        connections_to_keep: "{{ existing_connections | rejectattr('id', 'match', my_regex) | list }}"
      vars:
        my_regex: '[ {{ connection_ids[0] }} - {{ connection_ids[1] }} ]'
      
    # - debug: var=connections_to_keep 

    - name: Creating a new list of dictionary with modified and unmodified connections
      set_fact:
        new_connections: "{{ connections_modified |union(connections_to_keep) }}"  

    # - debug: var=new_connections  

    - name: Update Server Profile Template
      oneview_server_profile_template:
        config: "{{ config }}"
        state: present
        data:
          name: "{{ server_profile_template_name }}"
          connectionSettings:
            manageConnections: true
            complianceControl: Checked
            connections: "{{ new_connections }}"
