---

- name: Server profile template for RHEL with boot from local disk drives (RAID 1)
  hosts: localhost
  collections:
      - hpe.oneview
  gather_facts: no

  vars:
    config: "{{ playbook_dir }}/oneview_config.json"

    server_profile_template_name: "RHEL_BFLD"
    
    server_hardware_type_name: "SY 480 Gen10 1"
    enclosure_group_name: "EG"
    connection_network_management_name: "Management-Nexus"
    connection_fabric_A_name: "FC-A"
    connection_fabric_B_name: "FC-B"
    connection_network_set_name: "Production_network_set"
    
    synergy_service_pack_version: "SY-2021.05.03"

    storage_system_name: "3par.lj.lab"
    storage_pool_name: "SSD_r5"

    # Name of the existing datastore volume to present
    datastore_volume_name: "RHELFrame4DockerVolume"

    
  tasks:

# Gathering the necessary information to create the Server Profile Template

    - name: Gather facts about the Storage System "{{ storage_system_name }}" and its volume templates
      oneview_storage_system_facts:
        config: "{{ config }}"
        storage_hostname: "{{ storage_system_name }}"
        options:
          - templates
          - storagePools
        params:
          sort: 'name:descending'

    # - debug: var=storage_system_templates 
    # - debug: var=storage_systems 
    # - debug: var=storage_system_pools

    - name: Capture Storage System "{{ storage_system_name }}" uri 
      set_fact:
        storage_system_uri: "{{ (storage_systems |  map(attribute='uri') | list)[0] }}"

    # - debug: var=storage_system_uri

    - name: Gather facts about Firmware bundles
      oneview_firmware_driver_facts:
        config: "{{ config }}"
        # version: "{{ synergy_service_pack_version }}"
      delegate_to: localhost

    # - debug: var=firmware_drivers

    - name: Capture firmware bundle "{{ synergy_service_pack_version }}" uri
      set_fact:
        firmware_Baseline_Uri: "{{ (firmware_drivers | selectattr('version', 'equalto', synergy_service_pack_version) |  map(attribute='uri') | list)[0] }}"

    # - debug: var=firmware_Baseline_Uri  

    - name: Gather facts about the storage volume "{{ datastore_volume_name }}" on "{{ storage_system_name }}"
      oneview_volume_facts:
        config: "{{ config }}"
        name: "{{ datastore_volume_name }}"
      delegate_to: localhost

    # - debug: var=storage_volumes

    - name: Capture storage volume "{{ datastore_volume_name }}" uri on "{{ storage_system_name }}"
      set_fact:
        datastore_volume_uri: "{{ (storage_volumes |  map(attribute='uri') | list)[0] }}"

    # - debug: var=datastore_volume_uri        

# Creating the Server Profile Template

    - name: Create a server profile template for RHEL
      oneview_server_profile_template:
        config: "{{ config }}"
        state: present
        data:
          name: "{{ server_profile_template_name }}"
          description: "Server profile template for RHEL with boot from local disk drives (RAID 1)" 
          serverProfileDescription: "Server profile template for RHEL with boot from local disk drives (RAID 1)" 
          serverHardwareTypeName: "{{ server_hardware_type_name }}"
          enclosureGroupName: "{{ enclosure_group_name }}"
          affinity: Bay
          hideUnusedFlexNics: true
          macType: Virtual
          wwnType: Virtual
          serialNumberType: Virtual
          iscsiInitiatorNameType: AutoGenerated
          osDeploymentSettings:
          firmware:
            complianceControl: Checked
            firmwareActivationType: Immediate
            firmwareBaselineUri: "{{ firmware_Baseline_Uri }}"
            firmwareInstallType: FirmwareOnlyOfflineMode
            forceInstallFirmware: false
            manageFirmware: true
          connectionSettings:
            complianceControl: Checked
            manageConnections: true
            connections:
            - id: 1
              name: Mgmt1
              functionType: Ethernet
              networkName: "{{ connection_network_management_name }}"
              # portId: Mezz 3:1-a
              portId: Auto              
              # requestedVFs: '0'
              requestedMbps: '2500'
              # boot:
              #   priority: NotBootable
              #   bootVlanId:
              # lagName:
              managed: true
              # isolatedTrunk: false
              # networkName: 
            - id: 2
              name: Mgmt2
              functionType: Ethernet
              networkName: "{{ connection_network_management_name }}"
              # portId: Mezz 3:2-a
              portId: Auto                   
              # requestedVFs: '0'
              requestedMbps: '2500'
              # boot:
              #   priority: NotBootable
              #   bootVlanId:
              # lagName:
              managed: true
              # isolatedTrunk: false
              # networkName: 
            - id: 3
              name: FC-A
              functionType: FibreChannel
              networkName: "{{ connection_fabric_A_name }}"                
              # portId: Mezz 3:1-b
              portId: Auto                   
              # requestedVFs:
              requestedMbps: '2500'
              boot:
                priority: NotBootable
                # bootVlanId:
              # lagName:
              managed: true
              isolatedTrunk: false
              # networkName:
            - id: 4
              name: FC-B
              functionType: FibreChannel
              networkName: "{{ connection_fabric_B_name }}"    
              # portId: Mezz 3:2-b
              portId: Auto                   
              # requestedVFs:
              requestedMbps: '2500'
              boot:
                priority: NotBootable
                # bootVlanId:
              # lagName:
              managed: true
              isolatedTrunk: false
              # networkName:
            - id: 5
              name: 'NetworkSet1'
              functionType: Ethernet
              networkName: "{{ connection_network_set_name }}"                
              # portId: Mezz 3:1-d
              portId: Auto                   
              requestedVFs: '0'
              requestedMbps: '2500'
              boot:
                priority: NotBootable
                # bootVlanId:
              # lagName:
              managed: true
              isolatedTrunk: false
              # networkName:
            - id: 6
              name: 'NetworkSet2'
              functionType: Ethernet
              networkName: "{{ connection_network_set_name }}"  
              # portId: Mezz 3:2-d
              portId: Auto                   
              requestedVFs: '0'
              requestedMbps: '2500'
              boot:
                priority: NotBootable
                # bootVlanId:
              # lagName:
              managed: true
              isolatedTrunk: false
              # networkName:
          bootMode:
            complianceControl: Checked
            manageMode: true
            mode: UEFIOptimized
            pxeBootPolicy: Auto
            secureBoot: Unmanaged
          boot:
            complianceControl: Checked
            manageBoot: true
            order:
            - HardDisk
          bios:
            complianceControl: Checked
            manageBios: true
            overriddenSettings: 
              - id: WorkloadProfile
                value: Virtualization-MaxPerformance
              - id: MinProcIdlePower
                value: NoCStates
              - id: IntelUpiPowerManagement
                value: Disabled
              - id: MinProcIdlePkgState
                value: NoState
              - id: EnergyPerfBias
                value: MaxPerf
              - id: UncoreFreqScaling
                value: Maximum
              - id: PowerRegulator
                value: StaticHighPerf
              - id: SubNumaClustering
                value: Enabled
              - id: CollabPowerControl
                value: Disabled
              - id: EnergyEfficientTurbo
                value: Disabled
              - id: NumaGroupSizeOpt
                value: Clustered
          managementProcessor:
            complianceControl: Unchecked
            manageMp: false
            mpSettings: []
          localStorage:
            complianceControl: Checked
            sasLogicalJBODs: []
            controllers:
            - deviceSlot: Embedded
              mode: Mixed
              initialize: true
              driveWriteCache: Unmanaged
              predictiveSpareRebuild: Unmanaged
              logicalDrives:
              - name: RHEL_Boot
                raidLevel: RAID1
                bootable: true
                numPhysicalDrives: 2
                driveTechnology:
                sasLogicalJBODId:
                accelerator: Unmanaged
                numSpareDrives:
          sanStorage:
            complianceControl: CheckedMinimum
            manageSanStorage: true
            hostOSType: RHE Linux (5.x, 6.x, 7.x, 8.x)
            sanSystemCredentials: []
            volumeAttachments:
            - id: 1
              lun:
              lunType: Auto
              storagePaths:
              - connectionId: 4
                isEnabled: true
                targetSelector: Auto
                targets: []
              - connectionId: 3
                isEnabled: true
                targetSelector: Auto
                targets: []
              volumeUri: "{{ datastore_volume_uri }}"
              volume:
              isPermanent: true
              volumeStorageSystemUri: "{{ storage_system_uri }}"   
              bootVolumePriority: NotBootable

    - name: Displaying create completed message
      debug: 
        msg: 
         - "Server Profile Template '{{ server_profile_template_name }}' has been created successfully !"